### ISSUE TITLE
project status?

### ISSUE THREAD

**Issue by potier97** [Seeed-Studio/ArduPy#10]
Hello, I am very interested in this project and I would like to be able to contribute to this repo, since there are many libraries for the arduino IDE, and now the development with micropython, and especially with the arq ARM, is taking a lot of strength.

I say this since I have tried to rebuild some functional modules of Arduino and now I can pass them to the Micropython project.

Thank you

**Comment by LynnL4** [comment]
Hi,
   Thank you for your attention to this project. You can build your Ardupy firmware through [aip](https://github.com/Seeed-Studio/ardupy-aip). With aip, you can bind the converted Arduino library to microython. This is an example [seeed-ardupy-ultrasonic-sensor](https://github.com/Seeed-Studio/seeed-ardupy-ultrasonic-sensor)
