### ISSUE TITLE
Can ArduPy run on a Seeeduino lotus V 1.1 ?

### ISSUE THREAD

**Issue by sglebs** [Seeed-Studio/ArduPy#14]
Can ArduPy run in a https://wiki.seeedstudio.com/Grove_Beginner_Kit_for_Arduino/#seeeduino-lotus-v11 ? 

If yes, what are the steps?

If not yet - what needs do be done?

If impossible - what are the limitations that make it impossible?

Thanks!!!

**Comment by LynnL4** [comment]
Sorry, only samd21 and samd51 chips are supported at present.
